{{- range $deploymentKey, $deploymentVal := .Values.deployments }}
{{- $p := dict "deploymentKey" $deploymentKey }}
{{- $_ := set $p "Chart" $.Chart }}
{{- $_ := set $p "Release" $.Release }}
{{- $_ := merge $p . }}
{{- $_ := merge $p $.Values }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "repro.fullname" $p }}
  role: {{ $p.role }}
  someSetting: {{ $p.someSetting }}
{{ end }}